In [1]:
from dateutil.parser import parse as parse_date
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import spotipy
import spotipy.util as util

import pandas as pd
import spotipy
import spotipy.util as util
user_id = '1221063701'
client_id = 'a4a8320b97e84b88bc8f4585251085ce'
client_secret = '57f7dc998a714c61b8391858bdc5cc7c'
playlist_id = '5W9K5hiEUI2r7uj9VpX3Z2?si=fndGCxUVRAmIzkbWSEz3Zw'


token = util.prompt_for_user_token(user_id,
                                   'playlist-read-collaborative',
                                   client_id=client_id,
                                   client_secret=client_secret,
                                   redirect_uri='https://www.facebook.com/groups/1223037501082162')
sp = spotipy.Spotify(auth=token)

In [20]:
playlist = sp.user_playlist(user_id, playlist_id)
tracks = playlist['tracks']['items']
next_uri = playlist['tracks']['next']
for _ in range(int(playlist['tracks']['total'] / playlist['tracks']['limit'])):
    response = sp._get(next_uri)
    tracks += response['items']
    next_uri = response['next']

tracks_df = pd.DataFrame([(track['track']['id'],
                           track['track']['artists'][0]['name'],
                           track['track']['name'],
                           track['track']['popularity'],
                           parse_date(track['track']['album']['release_date']) if track['track']['album']['release_date'] else None,
                           parse_date(track['added_at']))
                          for track in playlist['tracks']['items']],
                         columns=['id', 'artist', 'name', 'popularity','release_date', 'added_at'] )

In [19]:
tracks_df.head(10)

,id,artist,name,popularity,release_date,added_at
0,2Lk8XTulavagQOrYqFpGB8,Billy Strings,Dust in a Baggie,58,2016-06-10,2020-10-10 00:56:10+00:00
1,2NGUXjeXcriG5O3ud1SNcm,Sturgill Simpson,Life Ain’t Fair and the World Is Mean,56,2020-10-16,2020-10-20 22:10:17+00:00
2,2su9lOnI21rEmHdBcWjM2B,Sturgill Simpson,All Around You,61,2020-10-16,2020-10-21 02:23:13+00:00
3,3QUG2aFOmRx48Zb2QChnoy,Black Joe Lewis & The Honeybears,Get Yo Shit,48,2009-01-11,2020-10-21 02:27:13+00:00
4,4JpazKcfOhbwqZrsYhzHee,Hozier,Jackie and Wilson,64,2014-09-19,2020-10-21 02:40:59+00:00
5,6PT1dLDHk9BaVwFG74pomG,Sturgill Simpson,Mercury in Retrograde,54,2019-09-27,2020-10-24 15:19:26+00:00
6,4xvB0wcMmNn7lcw1boRoA0,GRiZ,Where Will I Go,41,2020-09-17,2020-10-28 02:21:39+00:00
7,4dhARBZ8YLvm8oRDnCIeXr,Unknown Mortal Orchestra,Necessary Evil,62,2015-05-26,2020-10-24 03:10:23+00:00
8,26V4mdiCfPc5rQfhoRCo9j,J. Roddy Walston & The Business,Brave Man's Death,41,2010-07-27,2020-10-31 20:27:47+00:00
9,0z2TpISFncJ0F83Y5ZQciF,Cherub,Doo Doo Doo,39,2020-07-03,2020-11-10 00:49:39+00:00

In [6]:
tracks_df \
    .groupby('artist') \
    .count()['id'] \
    .reset_index() \
    .sort_values('id', ascending=False) \
    .rename(columns={'id': 'amount'}) \
    .head(10)

               artist  amount
19   Sturgill Simpson       3
0         Alina Baraz       1
1       Billy Strings       1
20  The Wood Brothers       1
18       Sara Watkins       1
17       Robert Ellis       1
16         Psymbionic       1
15       Paul Cauthen       1
14   Michael Kiwanuka       1
13       Leon Bridges       1